import { createHash } from 'crypto'
import { join } from 'path'
import { writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'

export interface AgreementData {
  title: string
  projectDescription: string
  collaboratorRole: string
  ipClause: string
  creditAgreement: string
  exitClause: string
  confidentiality: string
  milestoneSchedule: string
  initiatorName: string
  initiatorSignedAt: Date
  collaboratorName: string
  collaboratorSignedAt: Date
}

/**
 * Generates a simple mock PDF buffer for the Handshake Agreement.
 * In production, this would use a library like `pdf-lib` or a headless browser
 * to generate a real PDF document. For MVP/testing, we return a text buffer
 * containing the agreement details.
 */
export async function generateHandshakePDF(data: AgreementData): Promise<Buffer> {
  const content = `
HANDSHAKE AGREEMENT: ${data.title}
==================================================

Project Description
-------------------
${data.projectDescription}

Collaborator Role
-----------------
${data.collaboratorRole}

IP Clause: ${data.ipClause}
Credit Agreement: ${data.creditAgreement}
Exit Clause: ${data.exitClause}
Confidentiality: ${data.confidentiality}

Milestones
----------
${data.milestoneSchedule}


SIGNATURES
==================================================

Initiator: ${data.initiatorName}
Signed On: ${data.initiatorSignedAt.toISOString()}

Collaborator: ${data.collaboratorName}
Signed On: ${data.collaboratorSignedAt.toISOString()}

-- Document generated by Resurrect Trust Engine --
`

  // For real PDF, we'd do:
  // const pdfDoc = await PDFDocument.create()
  // ... draw text ...
  // return Buffer.from(await pdfDoc.save())

  return Buffer.from(content, 'utf-8')
}

/**
 * Mocks uploading the PDF to an S3 bucket.
 * In a real environment, this would use the AWS SDK `@aws-sdk/client-s3`.
 * For MVP/local, we write it to the local `/tmp/resurrect-agreements` dir.
 */
export async function uploadToS3(buffer: Buffer, filename: string): Promise<string> {
  const S3_BUCKET = process.env.AWS_BUCKET

  if (S3_BUCKET) {
    // Mocking AWS logic here:
    // const client = new S3Client({ region: 'us-east-1' })
    // await client.send(new PutObjectCommand({ Bucket: S3_BUCKET, Key: filename, Body: buffer }))
    // return filename
  }

  // Local fallback
  const uploadDir = join('/tmp', 'resurrect-agreements')
  if (!existsSync(uploadDir)) {
    await mkdir(uploadDir, { recursive: true })
  }

  const filePath = join(uploadDir, filename)
  await writeFile(filePath, buffer)

  return filePath
}

/**
 * Computes SHA-256 hash of a buffer for integrity verification.
 */
export function computePdfHash(buffer: Buffer): string {
  return createHash('sha256').update(buffer).digest('hex')
}
